#pragma once
#include "dmLayer.hpp"
#include "dmBiasLayer.hpp"
#include "dmFullyConnectedLayer.hpp"
#include "dmLinearMultLayer.hpp"
#include "dmOutputLayer.hpp"
#include "dmReLULayer.hpp"
#include "dmHyperbolicTan.hpp"
#include "dmConvolutionalLayer.hpp"